name: MLflow CI Training

on:
  push:
    branches: [main]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Check directory structure
      run: |
        ls -R

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow-env
        environment-file: Workflow-CI/MLProject/conda.yaml
        auto-activate-base: false

    - name: Run MLflow Project
      run: |
        cd Workflow-CI/MLProject
        mlflow run . --env-manager=conda -P n_neighbors=3
